				<footer class="footer text-right" style="left: 0;">
					<span class="pull-left"><strong><?= SITE_NAME ?></strong> <small>v21.11.0 <small>beta</small></small></span>
					© <?= date('Y') ?> <?= SITE_NAME ?>
				</footer>
				
			</div>
		</div>
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/bootstrap/js/popper.min.js"></script> -->
		<script src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/js/jquery.slimscroll.js"></script>
		<!-- <script src="< ?=URL_ROOT?>/assets/js/waves.js"></script> -->
		<!-- <script src="<?=URL_ROOT?>/assets/js/sidebarmenu.js"></script> -->
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script> -->
		<script src="<?=URL_ROOT?>/assets/plugins/moment/min/moment.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/js/custom.js"></script>
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/sparkline/jquery.sparkline.min.js"></script> -->
		<script src="<?=URL_ROOT?>/assets/plugins/blockUI/jquery.blockUI.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/sweetalert/sweetalert.min.js"></script>
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/typeahead.js-master/dist/typeahead.bundle.min.js"></script> -->
		<script src="<?=URL_ROOT?>/assets/plugins/inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/js/mask.init.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/datatables/jquery.dataTables.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/datatables/dataTables.buttons.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/datatables/buttons.print.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/datatables/jszip.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/datatables/pdfmake.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/datatables/vfs_fonts.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/datatables/buttons.html5.min.js"></script>
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/jquery-asColorPicker-master/libs/jquery-asColor.js"></script> -->
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/jquery-asColorPicker-master/dist/jquery-asColorPicker.min.js"></script> -->
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script> -->
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script> -->
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.es.js"></script> -->
		<!-- <link href="< ?= URL_ROOT ?>/assets/plugins/calendar/dist/fullcalendar.css" rel="stylesheet" /> -->
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/Chart.js/Chart.min.js"></script> -->
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/Chart.js/chartjs-plugin-datalabels.min.js"></script> -->
		<script src="<?=URL_ROOT?>/assets/plugins/select2/dist/js/select2.min.js" type="text/javascript"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/md5/md5.min.js"></script>
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/lightbox/js/lightbox.js"></script> -->
		<script src="<?=URL_ROOT?>/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/confirm/js/jquery-confirm.min.js"></script>
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/session-timeout/jquery.sessionTimeout.min.js"></script> -->
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/summernote/dist/summernote.min.js"></script> -->
		<!-- <script src="< ?=URL_ROOT?>/assets/plugins/jsBarcode/JsBarcode.all.min.js"></script> -->
		<!-- <script src="< ?= URL_ROOT ?>/assets/plugins/dropify/dist/js/dropify.min.js"></script> -->
		<!-- <script src="< ?= URL_ROOT ?>/assets/plugins/summernote-emoji-master/js/config.js"></script> -->
		<!-- <script src="< ?= URL_ROOT ?>/assets/plugins/summernote-emoji-master/js/tam-emoji.min.js"></script> -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js"></script>

		<script>
			$(function(){
				$(document).on('focusin', 'input, textarea', function() { $(this).select(); });
				$(document).on('focus', 'input, textarea', function() { item = $(this); setTimeout(() => { item.select(); }, 100); });
				$(document).on('mouseleave', '[data-toggle="tooltip"]', function() { $(document).find('.tooltip[role="tooltip"]').remove(); });

				<?php if( $_SESSION['diferencia'] >= 60 ) : ?>
					$('#form-pass').modal('show');

					$(".toggle-password").click(function () {
						let input = $(this).closest('.input-group').find("input");
						if (input.attr("type") === "password") {
							input.attr("type", "text");
							$(this).html('<i class="fa fa-eye-slash"></i>');
						} else {
							input.attr("type", "password");
							$(this).html('<i class="fa fa-eye"></i>');
						}
					});

					$('#pass-act').on('change', function () {
						validarPass($.trim($(this).val()), 'pass-act', 'Error. Ingrese su contraseña actual.');
					});

					$('#pass-new').on('change', function () {
						let pass = $.trim($(this).val());
						let regex = /^(?=.*[A-Za-z])(?=.*\d).{6,}$/;
						$('.alert').remove();

						if (regex.test(pass)) {
							validarPass(pass, 'pass-new', 'La nueva contraseña debe ser diferente a la contraseña actual');
						} else {
							$('#btnSavePass').attr('disabled', true).prop('disabled', true);
							mostrarError('pass-new', 'La nueva contraseña debe contener: *Al menos un número, *Al menos una letra y *Mínimo 6 caracteres');
							$('#pass-new').focus();
						}
					});

					$('#pass-new2').on('change', function () {
						let pass = $.trim($('#pass-new').val());
						let repeat = $.trim($('#pass-new2').val());
						$('.alert').remove();

						if (pass !== repeat) {
							mostrarError('pass-new2', 'Las contraseñas no coinciden');
							$('#pass-new2').val('').focus();
						}
					});

					$('#btnSavePass').on('click', function (e) {
						e.preventDefault();
						$('.alert').remove();

						let passActual = $.trim($('#pass-act').val());
						let passNew = $.trim($('#pass-new').val());
						let passRepeat = $.trim($('#pass-new2').val());

						if (passActual === '') {
							mostrarError('pass-act', 'Debe ingresar su contraseña actual.');
							return;
						}

						if (!/^(?=.*[A-Za-z])(?=.*\d).{6,}$/.test(passNew)) {
							mostrarError('pass-new', 'La nueva contraseña debe contener: *Al menos un número, *Al menos una letra y *Mínimo 6 caracteres');
							return;
						}

						if (passNew !== passRepeat) {
							mostrarError('pass-new2', 'Las contraseñas no coinciden');
							return;
						}

						// Validar la contraseña actual antes de proceder
						validarPass(passActual, 'pass-act', 'La contraseña actual es incorrecta', function () {
							let data = { password: passNew };

							$.post(`<?= URL_ROOT ?>/usuario/change/`, data, function (resp) {
								if (resp.response) {
									swal({ type:"success", title:"Listo!", text:'Contraseña actualizada exitosamente', timer:2000 });
									setTimeout(() => {
										location.reload();
									}, 3000);
								} else {
									mostrarError('pass-new', 'Error al actualizar la contraseña.');
								}
							}, 'json');
						});
					});

					function mostrarError(campo, mensaje) {
						let err = $('<div class="alert alert-danger mt-1 p-1"></div>').text(mensaje);
						$(`#${campo}`).closest('.input-group').after(err);

						setTimeout(() => {
							$('.alert').remove();
						}, 5000);
					}

					function validarPass(actual, campo, message, callback = null) {
						$('#btnSavePass').attr('disabled', true).prop('disabled', true);
						actual = encriptarPassword(actual);
						$.get(`<?= URL_ROOT ?>/usuario/validar/${actual}`, function (resp) {
							$('.alert').remove();

							let isValid = (campo === 'pass-act') ? resp.response : !resp.response;

							if (!isValid) {
								mostrarError(campo, message);
							} else {
								$('#btnSavePass').attr('disabled', false).prop('disabled', false);
								if (callback) callback(); // Ejecutar callback si se proporciona
							}
						}, 'json');
					}

					function encriptarPassword(password) {
						let sha1Hash = CryptoJS.SHA1(password).toString();						
						let md5Hash = CryptoJS.MD5(sha1Hash).toString();
						let reversedHash = md5Hash.split('').reverse().join('');
						return reversedHash;
					}
				<?php endif; ?>

				/* < ?php if($_SESSION['usuario']->usuario_tipo_id==1 && $vista!='Sala de espera' && !in_array(MOD_EMPL_NOBLOQUEO, $permisos)): ?>
				$.sessionTimeout({
					heading: 'h5',
					title: 'Sesión por expirar',
					message: 'Tu sesión está a punto de expirar. ¿Deseas seguir conectado?',
					countdownMessage: "Se cerrará en {timer} segundos.",
					warnAfter: 270000, 
					redirUrl: '< ?= URL_ROOT ?>/usuario/lock/'+encodeURIComponent(window.location.pathname+window.location.hash), 
					redirAfter: 300000, 
					keepAlive: true,
					keepAliveUrl: '< ?= URL_ROOT ?>/usuario/renovarToken/', 
					logoutUrl: '< ?= URL_ROOT ?>/usuario/logout', 
					keepAliveButton: 'Seguir conectado',
					logoutButton: 'Salir',
					ignoreUserActivity: false,
				});
				< ?php else: ?>
					setInterval(() => {
						$.post('< ?= URL_ROOT ?>/usuario/renovarToken/', function(resp) {}, 'json')
					}, 240000);
				< ?php endif; ?> */
			});
		</script>
	</body>
</html>