<?php include 'core/defines.php'; ?>
<!DOCTYPE html>
<html lang="es">
	<head>
	<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<!-- <link rel="icon" type="image/png" sizes="16x16" href="< ?=URL_ROOT?>/assets/images/favicon.ico"> -->
		<link rel="icon" type="image/png" sizes="16x16" href="<?=URL_ROOT?>/assets/images/favicon-32x32.png">
		<title><?= ucfirst($vista) . ' | ' . SITE_NAME ?></title>
		<link href="<?=URL_ROOT?>/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="<?=URL_ROOT?>/assets/css/style-admin.css" rel="stylesheet">
		<link href="<?=URL_ROOT?>/assets/css/colors/peek-dark.css" rel="stylesheet">
		<link href="<?=URL_ROOT?>/assets/plugins/sweetalert/sweetalert.css" rel="stylesheet" type="text/css">
		<style>
			.footer { left: 0; background-color: transparent; }
		</style>
	</head>
	<body>
		<div class="preloader">
			<svg class="circular" viewBox="25 25 50 50">
				<circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
		</div>
		<section id="wrapper">
			<div class="login-register">
				<div class="text-center m-b-30">
					<img src="<?=URL_ROOT?>/assets/images/Logo_ATM.png" alt="<?= SITE_NAME ?>" style="max-width: 250px">
				</div>
				<div class="login-box card">
					<div class="card-body">
						<form class="form-horizontal" id="loginform" action="index.html">
							<h3 class="box-title m-b-20">Bienvenido</h3>
							<div class="form-group ">
								<div class="col-xs-12">
									<div class="input-group mb-2">
										<div class="input-group-prepend">
											<div class="input-group-text"><span class="mdi mdi-mail-ru"></span></div>
										</div>
										<input class="form-control" type="text" required="" id="email" placeholder="matricula, usuario o correo">
									</div>
								</div>
							</div>
							<div class="form-group m-b-0">
								<div class="col-xs-12">
									<div class="input-group mb-2">
										<div class="input-group-prepend">
											<div class="input-group-text"><span class="mdi mdi-key"></span></div>
										</div>
										<input class="form-control" type="password" required="" id="password" placeholder="contraseña">
									</div>
								</div>
							</div>
							<div class="form-group text-center m-t-20 m-b-0">
								<div class="col-xs-12">
									<button class="btn btn-info btn-block text-uppercase waves-effect waves-light" id="btnLogin" type="button">Entra</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</section>
		<footer class="footer text-center text-white">
			© <?= date('Y') ?> <?= SITE_NAME ?> 
		</footer>
		<script src="<?=URL_ROOT?>/assets/plugins/jquery/jquery.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/js/jquery.slimscroll.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/moment/min/moment.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/js/custom.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/blockUI/jquery.blockUI.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/sweetalert/sweetalert.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/md5/md5.min.js"></script>
		<script>
			$(function(){
				$(".preloader").fadeOut();
				$apiUrl = '<?= URL_API ?>';
				$('#email').keyup(function(e) { if(e.keyCode == 13) doLogin(); });
				$('#password').keyup(function(e) { if(e.keyCode == 13) doLogin(); });
				$('#btnLogin').click(function() { doLogin(); });
				
				function doLogin(){
					email = $.trim($('#email').val());
					pass = $.trim($('#password').val());

					$('.alert').remove();
					err = $('<div class="alert alert-danger"></div>');
					if(email == '') {
						$(err).append('Debe ingresar el usuario o email');
						$('#btnLogin').parent().prepend(err);
						$('#email').focus();
					} else if(pass == '') {
						$(err).append('Debe ingresar la contraseña');
						$('#btnLogin').parent().prepend(err);
						$('#password').focus();
					} else {
						blockPage();
						$.post($apiUrl+'usuario/login/', {email: email, contrasena: pass}, function(resp) {
							if(resp.response){
								window.location.href = $apiUrl+'preguntas';
							} else {
								$(err).append(resp.message);
								$('#btnLogin').parent().prepend(err);
								$.unblockUI();
							}
						},'json');
					}
				}
			});
		</script>
	</body>
</html>